name: Publish

on:
  push:
    tags:
      - v* # Push events to version tags

jobs:
  publish:
    name: Publish
    needs: pack # From main.yml
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: package.tgz
        if: startsWith(github.ref, 'refs/tags/')
      - uses: actions/setup-node@v1
        with:
          node-version: 12
        if: startsWith(github.ref, 'refs/tags/')
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish package.tgz --access public
