name: Tags

on:
  push:
    tags:
    - v*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Typecheck
        run: npm run typecheck
      - name: Build 
        run: |
          npm run build
          npm pack
          mv *.tgz package.tgz
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: artifact
          path: package.tgz

  publish:
    name: Publish
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v1
        with:
          name: artifact
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org
      - name: Authenticate to npm
        run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - name: Publish to npm
        run: npm publish artifact/package.tgz --access public
